dist: bionic
language: ruby
services:
  - postgresql
addons:
  postgresql: 10
script: bundle exec rake test
before_script:
  - createdb distribute_reads_test_primary
  - createdb distribute_reads_test_replica
  - createdb distribute_reads_test_replica2
jobs:
  include:
    - rvm: 2.7
      gemfile: Gemfile
    - rvm: 2.6
      gemfile: test/gemfiles/activerecord52.gemfile
    - rvm: 2.5
      gemfile: test/gemfiles/activerecord51.gemfile
    - rvm: 2.4
      gemfile: test/gemfiles/activerecord50.gemfile
    - rvm: 2.7
      gemfile: Gemfile
      env: ADAPTER=mysql2
      services:
        - mysql
      before_script:
        - mysqladmin create distribute_reads_test_primary
        - mysqladmin create distribute_reads_test_replica
    - rvm: 2.7
      gemfile: test/gemfiles/makara3.gemfile
notifications:
  email:
    on_success: never
    on_failure: change
